#!/usr/bin/env bash

docker stop ExampleModule
docker rm ExampleModule
docker pull jack.hc-sc.gc.ca/php/php-base-laminas:latest

docker run -d --name ExampleModule \
    --net appnet \
    --restart unless-stopped \
    -v /etc/localtime:/etc/localtime:ro \
    -e PHP_DEV_ENV=1 \
    -e LAMINAS_ROOT_PATH="/var/www" \
    -v ./ExampleModule:/var/www/apps/ExampleModule \
    -v ./ExampleModuleWithUserAndApi:/var/www/apps/ExampleModuleWithUserAndApi \
    php-base-laminas:latest
