#!/usr/bin/env bash

docker stop ExampleModule
docker rm ExampleModule
docker pull jack.hc-sc.gc.ca/php/php-base-laminas:latest

docker run -d --name ExampleModule \
    -p 80:80 \
    --net appnet \
    --restart unless-stopped \
    -v /etc/localtime:/etc/localtime:ro \
    -e PHP_DEV_ENV=1 \
    -e LAMINAS_ROOT_PATH="/var/www" \
    -e JWT_SECRET="PLEASE CHANGE ME! Secret salt for the JWT. The longer the more secure. Should be unique for each environment. UzacJwlFjGNTB1j9NYrVBVku2t7vAAyTQYrkt9u9fIu5G75lvMz9L7Dw6stA4nLPVrpIRd3yf4s8pHvJFDEiJw4I1NkkgngUE5GkSqHpKycrN7J58nd9DdhUqsj6zTWRwCqpRyJdiCcgvq9BHKYMgrfSTLbqTjLzSsUzHeSl6OljhgttLYlSqrxbr3l12honWHiobNmMrBGvPfhWLH2GtXmc73X6OWqgIUmRp5Dn8jf95IgoRqoJjQFrv7rKB8ZBKMMWvtaXmBVlVyFKyUfDX8homxj1jDoFF3IJDWh8tsrQ" \
    -v ./ExampleModule:/var/www/apps/ExampleModule \
    -v ./ExampleModuleWithUserAndApi:/var/www/apps/ExampleModuleWithUserAndApi \
    php-base-laminas:latest
