#!/usr/bin/env bash

print_usage() {
    echo "Usage: ./${0} containerName sourcePath outputFile"
    echo " "
    echo "    cotnainerName => The name of the Laminas container (or child cotnainer)"
    echo "    sourcePath => the path the parse for strings"
    echo "    outputFile => where you want the .po file"
    echo " "

    textreset=$(tput sgr0) # reset the foreground colour
    bold=$(tput bold)
    red=$(tput setaf 1)
    whitebackground=$(tput setab 7)

    echo "${red}${bold} You need to provide exactly three (3) parameters ${textreset}"
    echo " "
    exit;
}

## since it requires args:
if [ $# != 3 ]
  then print_usage
fi

CONTAINER=${1}
INPUT=${2}
OUTPUT=${3}

docker exec -it $CONTAINER /var/www/vendor/bin/laminas translation:extract $INPUT /var/www/output.po
docker cp $CONTAINER:/var/www/output.po $OUTPUT
docker exec -it $CONTAINER rm /var/www/output.po
