laminas.example={};
laminas.example.strings={
    'you are logged in':'<?=$this->translate('You are logged in as %s.');?>',
    'logout':'<?=$this->translate('Logout');?>',
    'You can use any email and the password is "test"':'<?=$this->translate('You can use any email and the password is "test"');?>',
    'Email address':'<?=$this->translate('Email address');?>',
    'Password':'<?=$this->translate('Password');?>',
    'Remember me':'<?=$this->translate('Remember me');?>',
    'Use your your Windows username (or email)/password':'<?=$this->translate('Use your your Windows username (or email)/password');?>'
}
